# .project metadata for OSCAL-COMPASS
# Documentation: https://github.com/cncf/automation/tree/main/utilities/dot-project

schema_version: "1.0.0"
slug: "oscal-compass"
name: "OSCAL-COMPASS"
description: "The OSCAL COMPASS project is set of tools that enable the creation, validation, and governance of documentation artifacts for compliance needs. It leverages NIST's OSCAL (Open Security Controls Assessment Language) as a standard data format for interchange between tools and people, and provides an opinionated approach to OSCAL SDK and adoption by policy engines."
type: "project"
project_lead: "ancatri" # TODO: AUTO-DETECTED — please verify
slack_channels: # TODO: AUTO-DETECTED — please verify the channel(s) below
  - name: "#C06F3PEPNBW"
    link: "https://cloud-native.slack.com/archives/C06F3PEPNBW"
    primary: true
  - name: "#oscal-compass-trestle-agileauthoring-c2p"
  - name: "#welcome-to-the-oscal-compass-community-repository"

maturity_log:
  - phase: "sandbox"
    date: "2024-06-21T00:00:00Z"
    issue: "https://github.com/cncf/sandbox/issues/136" # TODO: AUTO-DETECTED — please verify

repositories:
  - "https://github.com/oscal-compass/compliance-trestle"

website: "https://github.com/oscal-compass/community"

artwork: "https://landscape.cncf.io/logos/oscal-compass-color-stacked.svg"

adopters:
   path: "https://github.com/oscal-compass/community/blob/main/ADOPTERS.md"

package_managers:
  pypi: "compliance-trestle"

security:
  policy:
    path: "https://github.com/oscal-compass/compliance-trestle/blob/develop/SECURITY.md"
  contact:
    advisory_url: "https://github.com/oscal-compass/compliance-trestle/security/advisories/new"

governance:
  contributing:
    path: "https://github.com/oscal-compass/compliance-trestle/blob/develop/CONTRIBUTING.md"
  code_of_conduct:
    path: "https://github.com/oscal-compass/.github/blob/main/CODE_OF_CONDUCT.md"

legal:
  license:
    path: "https://github.com/oscal-compass/compliance-trestle/blob/develop/LICENSE"
  identity_type:
    has_dco: true # AUTO-DETECTED — please verify
    has_cla: false # AUTO-DETECTED — please verify
    dco_url:
      path: "https://developercertificate.org/"

documentation:
  readme:
    path: "https://github.com/oscal-compass/compliance-trestle/blob/develop/README.md"

landscape:
  category: "Provisioning"
  subcategory: "Security & Compliance"

